name: Java Matrix 8 17 21 25 PR Build
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      project-dir:
        required: false
        type: string

jobs:
  build:
    strategy:
      matrix:
        tc: [ 8, 17, 21, 25 ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.project-dir }}
    env:
      BUILD_EVENT: ${{ github.event_name }}
      TARGET_COMPATIBILITY: ${{ matrix.tc }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          flag-name: tc${{ matrix.tc }}
