name: Java Matrix 8-25 Coveralls Release Build
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      project-dir:
        required: false
        type: string

jobs:
  build:
    strategy:
      matrix:
        tc: [ 8, 17, 21, 25 ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.project-dir }}
    env:
      BUILD_EVENT: ${{ github.event_name }}
      TARGET_COMPATIBILITY: ${{ matrix.tc }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Check out code
        uses: actions/checkout@v4
      - name: Prepare Gradle Script
        run: chmod +x gradlew && ./gradlew
      - name: Build, Sign and Publish Release
        run: ./gradlew clean compileJava publishToSonatype closeAndReleaseSonatypeStagingRepository
